name: SonarCloud Scanner

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: SonarCloud Scan
      run: mvn compile sonar:sonar -Dsonar.login=${{ secrets.SONARCLOUD_TOKEN }} -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=TheBusyBiscuit_CS-CoreLib2 -Dsonar.organization=thebusybiscuit-github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
